name: Actions Worflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Simple JS Action
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Qiushi
      - name: Log Greeting Time
        run: echo "${{ steps.greeting.outputs.time }}"
    
    