name: Experiment to enable corepack

on: [push, workflow_dispatch]

jobs: 
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: print node version
        run: |
          pwd
          ls
          node -v
          corepack -v
          npm -v
  
  with-setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Runtime
        uses: ./.github/actions/setup-runtime
      - name: print node version
        run: |
          node -v
          corepack -v
          yarn -v