name: pull request on release-prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - release-prod

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello World"
      - name: Dir
        run: pwd
      - name: List Files
        run: ls -lah
