name: Shell Commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multipe script
        run: |
          node -v
          npm -v
          yarn -v