name: Shell Commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls 
          ls -a
      - name: echo a string
        run: echo "Hello world"
      - name: multipe script
        run: |
          node -v
          npm -v
          yarn -v
      - name: python Commands
        run: |
          import platform
          print("Hello World")
          print("platform.processor()")
          print(platform.processor())
        shell: python
  run-window-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: Diretory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash